image:
  repository: tccr.io/truecharts/tautulli
  pullPolicy: IfNotPresent
  tag: 2.11.1@sha256:4c4086b6b73a1558a92d4e4567e667c948357740436e8b75a27e94e50a514a66

service:
  main:
    ports:
      main:
        port: 8181
        targetPort: 8181

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
