image:
  repository: tccr.io/truecharts/darktable
  pullPolicy: IfNotPresent
  tag: 3.8.1@sha256:2405588b7ed2b73066b2bed5a7e16868e8991c30a7264943447030248c24a037

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10129

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
