image:
  repository: tccr.io/truecharts/rstudio
  pullPolicy: IfNotPresent
  tag: v4.2.2@sha256:0902a2549c17caf1a4755f95b804685659b2162b3325d2483ad20cefc20d1db6

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

secretEnv:
  USER: rstudio
  PASSWORD: rstudio

env:
  DISABLE_AUTH: false
  ROOT: "FALSE"
  USERID: "{{ .Values.podSecurityContext.runAsUser }}"
  GROUPID: "{{ .Values.podSecurityContext.fsGroup }}"

service:
  main:
    ports:
      main:
        port: 8787
        protocol: HTTP
        targetPort: 8787

persistence:
  config:
    enabled: true
    mountPath: /home/rstudio/.config/rstudio
  workspace:
    enabled: true
    mountPath: /home/rstudio/workspace

portal:
  enabled: true
