image:
  repository: tccr.io/truecharts/watchyourlan
  tag: 0.8.1@sha256:94767576c246d317e6283cf42bbb66014f6d08b8e34215825864eb0fc09ab930
  pullPolicy: IfNotPresent

hostNetwork: true

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

watchyourlan:
  gui_ip: "0.0.0.0"
  interfaces:
    - enp1s0
  theme: darkly
  timeout: 300
  shoutrrr_url: ""

env:
  GUIPORT: "{{ .Values.service.main.ports.main.port }}"
  DBPATH: /data/db.sqlite
  # User Defined
  GUIIP: "{{ .Values.watchyourlan.gui_ip }}"
  IFACE: '{{ join " " .Values.watchyourlan.interfaces }}'
  THEME: "{{ .Values.watchyourlan.theme }}"
  TIMEOUT: "{{ .Values.watchyourlan.timeout }}"
  SHOUTRRR_URL: "{{ .Values.watchyourlan.shoutrrr_url }}"

probes:
  liveness:
    type: HTTP
    path: /
  readiness:
    type: HTTP
    path: /
  startup:
    type: HTTP
    path: /

service:
  main:
    ports:
      main:
        port: 10355
        protocol: HTTP

persistence:
  data:
    enabled: true
    mountPath: "/data"

portal:
  enabled: true
