env:
  PORT: "3000"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/vertex
  tag: vstable@sha256:80e4fd692b722da032e1b9e8f7b8d8e6c664f64464faeab3e3de1ae14716fa77
persistence:
  config:
    enabled: true
    mountPath: /vertex
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 3000
        protocol: TCP
        targetPort: 3000

portal:
  enabled: true
