image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/plextraktsync
  tag: latest@sha256:8ace21b5e32fc9fd3e841885ecce3bf36a9076c339f57376374f90275f1b2643

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

tty: true
stdin: true

plexTraktSync:
  task: ""
  schedule: "0 */6 * * *"

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

persistence:
  config:
    enabled: true
    mountPath: /app/config

portal:
  enabled: false

cronjob:
  annotations: {}
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 2
