image:
  repository: tccr.io/truecharts/logitechmediaserver
  pullPolicy: IfNotPresent
  tag: 8.4.0@sha256:7a36644ba631c62c8eabb67f88ce7b945a32271175e82cb72d3f38a98d8072bd

env:
  HTTP_PORT: "{{ .Values.service.main.ports.main.port }}"

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 9000
  cli:
    enabled: true
    ports:
      cli:
        enabled: true
        port: 9090
        targetPort: 9090
  playertcp:
    enabled: true
    ports:
      slimprototcp:
        enabled: true
        port: 3483
        targetPort: 3483
  playerudp:
    enabled: true
    ports:
      slimprotoudp:
        enabled: true
        port: 3483
        protocol: UDP
        targetPort: 3483

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  enabled: true
