image:
  repository: tccr.io/truecharts/calibre-web
  pullPolicy: IfNotPresent
  tag: 0.6.19@sha256:c3f129199b32e9e2ccd9837f139919e86eb153479ea15fe312014ec02cd49c24

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8083
        targetPort: 8083

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
