env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/auto-yt-dl
  tag: latest@sha256:8498eb01ebcf86680dc29b4a883413e135906ab2c94f37d3f0f4a38e5993424e
persistence:
  data:
    enabled: true
    mountPath: /app/data
  hostpath1:
    enabled: true
    mountPath: /app/Downloads
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 5000
        protocol: TCP
        targetPort: 5000

portal:
  enabled: true
