env:
  CUSTOM_RES_H: "768"
  CUSTOM_RES_W: "1280"
  EXTRA_PARAMETERS: ""
  UMASK: "000"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/chromium
  tag: latest@sha256:9a42d4918f738d8b73324501f0c58d94b4f3447ac0da00e89cff16b09c97df5a
persistence:
  datadir:
    enabled: true
    mountPath: /chrome
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8080
        protocol: TCP
        targetPort: 8080

portal:
  enabled: true
