env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/sourcegraph
  tag: 4.3.0@sha256:ef41ec7c43ca1829a378cd78b7b72ebc2335d2490b4325f1878ee2924c77bd2d
persistence:
  applicationdatastoragepath:
    enabled: true
    mountPath: /var/opt/sourcegraph
  configstoragepath:
    enabled: true
    mountPath: /etc/sourcegraph
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  adminconsolepo:
    enabled: true
    ports:
      adminconsolepo:
        enabled: true
        port: 2633
        protocol: TCP
        targetPort: 2633
  grafanaport:
    enabled: true
    ports:
      grafanaport:
        enabled: true
        port: 3370
        protocol: TCP
        targetPort: 3370
  main:
    ports:
      main:
        port: 7080
        protocol: HTTP
        targetPort: 7080

portal:
  enabled: true
