env:
  VNC_PW: unraid
  VNC_RESOLUTION: 1360x768
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/firefox-desktop-g3
  tag: latest@sha256:ce5b0b6f0e6630a1e61513f8fe97c105cc9e4367ed9922f9efdd7273d397e515
persistence:
  internalshare:
    enabled: true
    mountPath: /UNRAID_SHARE
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 6901
        protocol: HTTP
        targetPort: 6901
  webuivnc:
    enabled: true
    ports:
      webuivnc:
        enabled: true
        port: 5901
        protocol: TCP
        targetPort: 5901

portal:
  enabled: true
