image:
  repository: tccr.io/truecharts/lazylibrarian
  pullPolicy: IfNotPresent
  tag: latest@sha256:ba05ebe09005329f37583fda1a47b643fdbe8a168189ef0d6c48816bb7c697be

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 5299
        targetPort: 5299

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
