image:
  repository: tccr.io/truecharts/openspeedtest
  pullPolicy: IfNotPresent
  tag: latest@sha256:c1126710cb9f5091322292a3dc0b957462bce948d4c6f3b5f4ddba2960382913

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 3000
        port: 10256

portal:
  enabled: true
