image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/adminer
  tag: latest@sha256:0d905060276ce8d471e6230f3abd2d4bd5acd7784886c5b7f0c64d923142d521
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

env:
  ADMINER_DESIGN: ""
  ADMINER_PLUGINS: ""

service:
  main:
    ports:
      main:
        port: 18080
        protocol: HTTP
        targetPort: 8080

portal:
  enabled: true
