image:
  repository: tccr.io/truecharts/domoticz
  pullPolicy: IfNotPresent
  tag: 2022.2.20221215@sha256:312ef30cc351213fff1ce0e383f66ca62a9eb9e96d9b05ae36ed3aac63004982

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  WEBROOT: "domoticz"

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10144
  comm1:
    enabled: true
    ports:
      comm1:
        enabled: true
        targetPort: 6144
        port: 6144
  comm2:
    enabled: true
    ports:
      comm2:
        enabled: true
        targetPort: 1443
        port: 1443

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
