image:
  repository: tccr.io/truecharts/flexget
  pullPolicy: IfNotPresent
  tag: 3.5.13@sha256:b024cb4dd9f25449e0f28120aa96c5a4aafa718034253dcc547faf06ebe91d33

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10174
        targetPort: 5050

env:
  FG_LOG_LEVEL: info
  FG_LOG_FILE: flexget.log

secretEnv:
  FG_WEBUI_PASSWD: "jLeT78KBDPW"

persistence:
  config:
    enabled: true
    mountPath: "/config"

  data:
    enabled: true
    mountPath: "/data"

portal:
  enabled: true
