image:
  repository: tccr.io/truecharts/nexusoss
  pullPolicy: IfNotPresent
  tag: 3.45.0@sha256:f58de4ad367a41f75e42cf9330a3ff944d6000afedd7a74065839ae8a024cb80

podSecurityContext:
  runAsGroup: 200
  runAsUser: 200
  fsGroup: 200

env:
  INSTALL4J_ADD_VM_PARAMS: "-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs"

service:
  main:
    ports:
      main:
        port: 10288
        targetPort: 8081

persistence:
  data:
    enabled: true
    mountPath: /nexus-data

portal:
  enabled: true
