image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/rdesktop
  tag: latest@sha256:b34ab4f996c1e46e68fd39381dd4ee2ff318551e5ff0aebc2f4f8a1615ceeb98
ubuntuXFCEImage:
  repository: tccr.io/truecharts/rdesktop-ubuntu-xfce
  tag: latest@sha256:eeba28bdf4514b66f744ed1204a4ca79c5d27277a32c98cb2e2541bdf483ecb5
  pullPolicy: Always
fedoraXFCEImage:
  repository: tccr.io/truecharts/rdesktop-fedora-xfce
  tag: latest@sha256:d39854437b6d40045e7c2469b1924714820db1af3e4498672ec3335b0ae55d16
  pullPolicy: Always
archXFCEImage:
  repository: tccr.io/truecharts/rdesktop-arch-xfce
  tag: latest@sha256:2cc4840728a5b97b1a6db94c49f2e7426765af006764db4d5b4ca20d37ab8d97
  pullPolicy: Always

alpineKDEImage:
  repository: tccr.io/truecharts/rdesktop-alpine-kde
  tag: latest@sha256:75f13464354880198596d945dd14c3feb1df58a4cbb76faf9f0fdeae4fab8249
  pullPolicy: Always
ubuntuKDEImage:
  repository: tccr.io/truecharts/rdesktop-ubuntu-kde
  tag: latest@sha256:c71e0b8ce50b5223090509302415c6b8b9dfec784d661c3136c92abaf169b328
  pullPolicy: Always
fedoraKDEImage:
  repository: tccr.io/truecharts/rdesktop-fedora-kde
  tag: latest@sha256:fb931fdf7b7b654ca506de372993c94e5daa15f9d04725ac6f85feb33929aa4d
  pullPolicy: Always
archKDEImage:
  repository: tccr.io/truecharts/rdesktop-arch-kde
  tag: latest@sha256:4c03701bb16e65cd9b31aebc73ff9a1bd4b856ee35a7b42c113e898547f5667a
  pullPolicy: Always

alpineMATEImage:
  repository: tccr.io/truecharts/rdesktop-alpine-mate
  tag: latest@sha256:ed69673c3828021907ba2c2e573248af3fc09d715688fe60b16454eec5bc3ab7
  pullPolicy: Always
ubuntuMATEImage:
  repository: tccr.io/truecharts/rdesktop-ubuntu-mate
  tag: latest@sha256:e0383151b9f77d0a513cef73958301be2771ba857f48be1057a523f694df4a11
  pullPolicy: Always
fedoraMATEImage:
  repository: tccr.io/truecharts/rdesktop-fedora-mate
  tag: latest@sha256:eb262f76da379bc00c8627363d06aba6e14149f311f0bc64ad30746857cb4993
  pullPolicy: Always
archMATEImage:
  repository: tccr.io/truecharts/rdesktop-arch-mate
  tag: latest@sha256:d9801d6d79d732d0dad3077df65ea9a06a21edf8468206da31bc8cfec9425f5b
  pullPolicy: Always

alpineI3Image:
  repository: tccr.io/truecharts/rdesktop-alpine-i3
  tag: latest@sha256:8465936140c7b246874cb9ea131da1fb52e2fbcad7dea3725b5af2ebf85d9412
  pullPolicy: Always
ubuntuI3Image:
  repository: tccr.io/truecharts/rdesktop-ubuntu-i3
  tag: latest@sha256:cfecf367f69ab01dc6c1b5f239e990a49bbe9b3883e7c916cc3f0f6e1998ddb9
  pullPolicy: Always
fedoraI3Image:
  repository: tccr.io/truecharts/rdesktop-fedora-i3
  tag: latest@sha256:e89bc02fb1f579e53a10ebb4ceecfde00e3c95dd57a01c601488727a2e14b83b
  pullPolicy: Always
archI3Image:
  repository: tccr.io/truecharts/rdesktop-arch-i3
  tag: latest@sha256:c1e6a2b31d3e5df8a3ec47730c3d26aa38cd1e735393a93aaa5de6b828091d49
  pullPolicy: Always

alpineOpenBoxImage:
  repository: tccr.io/truecharts/rdesktop-alpine-openbox
  tag: latest@sha256:840d99b48819273961f58f4b7a9cffbcf4331f284917f9c9b26c9c7236e6e226
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: tccr.io/truecharts/rdesktop-ubuntu-openbox
  tag: latest@sha256:44f56813827b45d7e51571fa1af7e3b394faa664f5bb613c5fec0a835a762fea
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: tccr.io/truecharts/rdesktop-fedora-openbox
  tag: latest@sha256:a84fa3f266745e9577f15a47e2dcd0ba86d36d83632f2cb60558c72b25dbda4d
  pullPolicy: Always
archOpenBoxImage:
  repository: tccr.io/truecharts/rdesktop-arch-openbox
  tag: latest@sha256:8378f8aa400948c6486bd3086275f78387b8b7a2b7eee3e9dab540cd5edfde5e
  pullPolicy: Always

alpineICEWMImage:
  repository: tccr.io/truecharts/rdesktop-alpine-icewm
  tag: latest@sha256:f717268769210f177a9359aa0715ae71f123ea22dc0516b7200de0ce8202aaf6
  pullPolicy: Always
ubuntuICEWMImage:
  repository: tccr.io/truecharts/rdesktop-ubuntu-icewm
  tag: latest@sha256:c6fb91ca3ee3f0cc3b341ba47c55d3eeab1b58f942cc4d8596639fc8b2de3059
  pullPolicy: Always
fedoraICEWMImage:
  repository: tccr.io/truecharts/rdesktop-fedora-icewm
  tag: latest@sha256:ba3b33376fc366ec168206b424d3d215eb395128db8e8fa8f20a320f22c4368e
  pullPolicy: Always
archICEWMImage:
  repository: tccr.io/truecharts/rdesktop-arch-icewm
  tag: latest@sha256:e3eafe388f32f7002f667116796f45f60d0ccf606de1adb77ffd44aa3866e7e0
  pullPolicy: Always

imageSelector: image

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  main:
    ports:
      main:
        port: 3389
        protocol: HTTP
        targetPort: 3389

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  enabled: true
