env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/tubearchivist-redisjson
  tag: latest@sha256:83229b3c91ec4a3b33b43946c9c0442978e65bb4f3fe78e2a41523cbade7a57e
persistence:
  data:
    enabled: true
    mountPath: /data
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 6379
        protocol: TCP
        targetPort: 6379

portal:
  enabled: true
