image:
  repository: tccr.io/truecharts/minio-console
  tag: 0.22.3@sha256:c168025d1593142ba0a87bc2f18202efb8803ba707cba4f1af202bb0cbd266db
  pullPolicy: IfNotPresent

args: ["server"]

secretEnv:
  CONSOLE_PBKDF_PASSPHRASE: "changeme"
  CONSOLE_PBKDF_SALT: "changeme"

env:
  CONSOLE_MINIO_SERVER: ""

service:
  main:
    ports:
      main:
        port: 9090
        targetPort: 9090

securityContext:
  readOnlyRootFilesystem: false

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
