image:
  repository: tccr.io/truecharts/speedtest-tracker
  tag: latest@sha256:74babc7a90b549940b1b35ab84dfbfe325e92492a6482928d189e039e279b1bf
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  DB_CONNECTION: pgsql
  DB_PORT: 5432
  DB_DATABASE: "{{ .Values.postgresql.postgresqlDatabase }}"
  DB_USERNAME: "{{ .Values.postgresql.postgresqlUsername }}"
  DB_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost
  DB_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password

service:
  main:
    ports:
      main:
        port: 8765
        protocol: HTTPS
        targetPort: 443

persistence:
  config:
    enabled: true
    mountPath: /config

postgresql:
  enabled: true
  existingSecret: dbcreds
  postgresqlDatabase: speedtest_tracker
  postgresqlUsername: speedtest_tracker

portal:
  enabled: true
