env:
  SIA_API_PASSWORD: ""
  SIA_WALLET_PASSWORD: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/sia-daemon
  tag: vmaster@sha256:14ecab016a0e9af0de3fa04a3f4afd30100ab992b55ae79760f11398d466d2af
persistence:
  datadirectory:
    enabled: true
    mountPath: /sia-data
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  hostrhp2port:
    enabled: true
    ports:
      hostrhp2port:
        enabled: true
        port: 9982
        protocol: TCP
        targetPort: 9982
  hostrhp3port:
    enabled: true
    ports:
      hostrhp3port:
        enabled: true
        port: 9983
        protocol: TCP
        targetPort: 9983
  main:
    ports:
      main:
        port: 9981
        protocol: TCP
        targetPort: 9981

portal:
  enabled: true
