image:
  repository: tccr.io/truecharts/filezilla
  pullPolicy: IfNotPresent
  tag: 3.59.0@sha256:a541206174f5364873d0347587b10575f1800aba44df6734b6b860b7c5a2613b

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10035
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
