image:
  repository: tccr.io/truecharts/strapi
  tag: 4.5.5@sha256:dfb09c1c66113f781df7cb0911bab3122c9ca0a2e8a593b4c7b66635eec968c5
  pullPolicy: Always

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  JWT_SECRET: "my_jwt_secret"
  ADMIN_JWT_SECRET: "my_admin_jwt_secret"
  APP_KEYS: "my_app_keys"

env:
  DATABASE_CLIENT: "postgres"
  DATABASE_PORT: 5432
  DATABASE_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  DATABASE_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost
  DATABASE_USERNAME: "{{ .Values.postgresql.postgresqlUsername }}"
  DATABASE_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  # STRAPI_LICENSE
  NODE_ENV: "production"
  STRAPI_DISABLE_UPDATE_NOTIFICATION: true
  FAST_REFRESH: false
  EXTRA_ARGS: ""

service:
  main:
    ports:
      main:
        port: 1337
        targetPort: 1337

persistence:
  data:
    enabled: true
    mountPath: "/srv/app"

# Enabled postgres
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: strapi
  postgresqlDatabase: strapi

portal:
  enabled: true
