env:
  UMASK: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/cops
  tag: latest@sha256:90999a44b37d962525ce9fbc1de1839b37855e214e9dc69ec7a8c804fdcc7ef5
persistence:
  config:
    enabled: true
    mountPath: /config
  pathbooks:
    enabled: true
    mountPath: /books
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 80
        protocol: TCP
        targetPort: 80

portal:
  enabled: true
