image:
  repository: tccr.io/truecharts/pylon
  pullPolicy: IfNotPresent
  tag: 2.9.0@sha256:ee04d55dd782ad75f125ba647d4250f0e4c8416699e75eff1cfedcc2fe187312

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  PYUSER: ""
  PYPASS: ""

env:
  GITURL: ""

service:
  main:
    ports:
      main:
        targetPort: 3131
        port: 3131

persistence:
  code:
    enabled: true
    mountPath: "/code"
  varrun:
    enabled: true

portal:
  enabled: true
