image:
  repository: tccr.io/truecharts/budge
  tag: v0.0.9@sha256:6c360237d7f48ccd4e4ba39f298dea91fe940b81e4b8a43f21ccaed72a88c10e
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  NODE_ENV: "production"

service:
  main:
    ports:
      main:
        port: 10165
        targetPort: 80

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
