image:
  repository: tccr.io/truecharts/openvscode-server
  pullPolicy: IfNotPresent
  tag: 1.75.0@sha256:f0c53e4f1fc973abf05a40e4e5113733990cf2a656c7697d33786d19e5d43826

# portal:
# path: "/?tkn={{ .Values.secret.CONNECTION_TOKEN }}"

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

# secretEnv:
#   CONNECTION_TOKEN: "somerandomstring"
#   CONNECTION_SECRET: ""
#   SUDO_PASSWORD: ""

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10135

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
