image:
  repository: tccr.io/truecharts/rsnapshot
  pullPolicy: IfNotPresent
  tag: 1.4.4@sha256:8b5c9bb499e186e93d9dd518471be0d708f2af2079285d789097f85a7ebf21f3

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: false
