image:
  repository: tccr.io/truecharts/autobrr
  pullPolicy: IfNotPresent
  tag: 1.12.1@sha256:1a22a218d2ee445b422f7988bfc53ba1c203231490f63b5e80e33bf63f695caa

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 7474
        targetPort: 7474

probes:
  liveness:
    enabled: true
    custom: true
    spec:
      exec:
        command:
          - /bin/sh
          - -c
          - curl --fail localhost:7474/
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
  readiness:
    enabled: true
    custom: true
    spec:
      exec:
        command:
          - /bin/sh
          - -c
          - curl --fail localhost:7474/
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
  startup:
    enabled: false

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
