image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/searx
  tag: latest@sha256:fef9545d8334a9ebb32a7581c609973e6cc0c023fc37cb620299e501075811a6

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

env:
  BASE_URL: ""

service:
  main:
    ports:
      main:
        port: 8080
        protocol: TCP
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: /etc/searx

portal:
  enabled: true
