env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/chronograf
  tag: latest@sha256:eb0607b158d6ea281fcf2af8e5300c957cd7ee85d2439910c43b3915276fb97c
persistence:
  chronograf:
    enabled: true
    mountPath: /var/lib/chronograf
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8888
        protocol: TCP
        targetPort: 8888

portal:
  enabled: true
