image:
  repository: tccr.io/truecharts/uptime-kuma
  pullPolicy: IfNotPresent
  tag: 1.19.2@sha256:f66869f866f401cceb8a4b57af40a7543175627c32ec5dd83266a4f161a0297f

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

security:
  PUID: 0

service:
  main:
    ports:
      main:
        port: 3001
        targetPort: 3001

persistence:
  config:
    enabled: true
    mountPath: "/app/data"

portal:
  enabled: true

metrics:
  # -- Enable and configure a Prometheus serviceMonitor for the chart under this key.
  # @default -- See values.yaml
  enabled: false
  serviceMonitor:
    interval: 1m
    scrapeTimeout: 30s
    labels: {}
