env:
  UMASK: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/apprise-api
  tag: latest@sha256:61284eef42f0e777313716b1c09b103fac539ee177a0503f0f7c2b3031e26a0d
persistence:
  config:
    enabled: true
    mountPath: /config
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8000
        protocol: TCP
        targetPort: 8000

portal:
  enabled: true
