image:
  repository: tccr.io/truecharts/bazarr
  pullPolicy: IfNotPresent
  tag: 1.1.3@sha256:f1a56b156ea13ea53559e8a8f00b776c3122be0766b46b34dc16ca9a4f9252c3

service:
  main:
    ports:
      main:
        port: 6767
        targetPort: 6767

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
