env:
  VNC_PASSWD: "123456"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/obs-ndi
  tag: latest@sha256:97698f9e2418aedc5b6b906571f14cbb7d177b69db181ceea67a31e8b49121e1
persistence:
  configpath:
    enabled: true
    mountPath: /config/obs-studio
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 5901
        protocol: TCP
        targetPort: 5901

portal:
  enabled: true
