image:
  repository: tccr.io/truecharts/immich-server
  tag: 1.39.0_61@sha256:150bc50169418d4b6da875cc29a07a7dfa1194a41d48fb42b9e45a5d7676d850
  pullPolicy: IfNotPresent

mlImage:
  repository: tccr.io/truecharts/immich-ml
  tag: 1.40.1_63@sha256:3d37159579cabb41ca2c9d870ac087b624f079f64200753d5bc99f0fcf6200f5
  pullPolicy: IfNotPresent

webImage:
  repository: tccr.io/truecharts/immich-web
  tag: 1.39.0_61@sha256:213fbb0cd372d9e22141656605045d959a0888d51a8e95a772fcb4f1684354ff
  pullPolicy: IfNotPresent

proxyImage:
  repository: tccr.io/truecharts/immich-proxy
  tag: 1.39.0_61@sha256:97994bf419d6cb1a318827896cc7927dfbab8e162153f4b1e61ae179095146cb
  pullPolicy: IfNotPresent

command:
  - /bin/sh
  - ./start-server.sh

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

immich:
  enable_ml: true
  public_login_page_message: Immich
  disable_reverse_geocoding: false
  reverse_geocoding_precision: 3
  # simple | verbose
  log_level: simple
  mapbox_enable: false
  mapbox_key: ""

envFrom:
  - configMapRef:
      name: '{{ include "tc.common.names.fullname" . }}-server-config'
  - configMapRef:
      name: '{{ include "tc.common.names.fullname" . }}-common-config'
  - secretRef:
      name: '{{ include "tc.common.names.fullname" . }}-immich-secret'

probes:
  liveness:
    path: /server-info/ping
    type: HTTP
    port: 3001
  readiness:
    path: /server-info/ping
    type: HTTP
    port: 3001
  startup:
    path: /server-info/ping
    type: HTTP
    port: 3001

service:
  main:
    ports:
      main:
        port: 10323
        protocol: HTTP
        targetPort: 8080

persistence:
  uploads:
    enabled: true
    mountPath: /usr/src/app/upload

postgresql:
  enabled: true
  existingSecret: dbcreds
  postgresqlUsername: immich
  postgresqlDatabase: immich

redis:
  enabled: true
  existingSecret: rediscreds

portal:
  enabled: true
