image:
  repository: tccr.io/truecharts/cyberchef
  tag: 9.55.0@sha256:632a912cb0246c49e84e365744e6aa582a7bc8117dc74e30548cc4a96b1de88c
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10219
        targetPort: 8000

portal:
  enabled: true
