env:
  EXTRA_JAVA_OPTIONS: -Xms512m -Xmx4g
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/artifactory-oss
  tag: 7.47.14@sha256:f8ce3f2c2c04a6f084ccf3867a61ad9a263325e16e11f3ba8b0d28ecb3775cc1
persistence:
  varoptjfrogartifactory:
    enabled: true
    mountPath: /var/opt/jfrog/artifactory
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8181
        protocol: TCP
        targetPort: 8081

portal:
  enabled: true
