image:
  repository: tccr.io/truecharts/mosdns
  pullPolicy: IfNotPresent
  tag: 4.5.3@sha256:3acef30fa1b4b685ccc84f360bb41a3f3592cdce9b5f3e3e94668c1d153bf560

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 53
        port: 53
  dns-udp:
    enabled: true
    ports:
      dns-upd:
        enabled: true
        protocol: UDP
        targetPort: 53
        port: 53

persistence:
  data:
    enabled: true
    mountPath: "/etc/mosdns"

portal:
  enabled: false
