apiVersion: v2
appVersion: "1.13.3"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.1.2
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.truecharts.org/
    version: 11.0.17
  - condition: redis.enabled
    name: redis
    repository: https://charts.truecharts.org
    version: 5.0.22
description: Baserow is an open source no-code database tool and Airtable alternative.
home: https://truecharts.org/charts/stable/baserow
icon: https://truecharts.org/img/hotlink-ok/chart-icons/baserow.png
keywords:
  - baserow
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: baserow
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/baserow
  - https://hub.docker.com/r/baserow/baserow
  - https://gitlab.com/bramw/baserow/
version: 6.0.19
annotations:
  truecharts.org/catagories: |
    - productivity
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
