image:
  repository: tccr.io/truecharts/baserow
  tag: 1.13.3@sha256:e6b636a65e2c8782717ec7a2d5c30c336e77bebad95cb3c4e4f212430a5aa514
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  DATABASE_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  DATABASE_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  DATABASE_PORT: "5432"
  REDIS_USER: "{{ .Values.redis.redisUsername }}"
  REDIS_PORT: "6379"
  REDIS_PROTOCOL: "redis"
  BASEROW_CADDY_ADDRESSES: ":{{ .Values.service.main.ports.main.port }}"
  # User Defined
  BASEROW_PUBLIC_URL: "http://localhost:10228"
  FROM_EMAIL: ""
  EMAIL_SMTP: ""
  EMAIL_SMTP_USE_TLS: ""
  EMAIL_SMTP_HOST: ""
  EMAIL_SMTP_PORT: 587
  EMAIL_SMTP_USER: ""
  EMAIL_SMTP_PASSWORD: ""
  DATABASE_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost
  DATABASE_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  REDIS_HOST:
    secretKeyRef:
      name: rediscreds
      key: plainhost
  REDIS_PASSWORD:
    secretKeyRef:
      name: rediscreds
      key: redis-password
  SECRET_KEY:
    secretKeyRef:
      name: baserow-secrets
      key: SECRET_KEY

probes:
  liveness:
    path: "/_health"
  readiness:
    path: "/_health"
  startup:
    path: "/_health"

service:
  main:
    ports:
      main:
        port: 10228

persistence:
  data:
    enabled: true
    mountPath: "/baserow/data"

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: baserow
  postgresqlDatabase: baserow

redis:
  enabled: true
  existingSecret: "rediscreds"
  redisUsername: "default"

portal:
  enabled: true
