image:
  repository: tccr.io/truecharts/xwiki
  tag: 14.10.2-postgres@sha256:36ab09e1245eb82851f17bd3bf6e64720f4e04d05ad38381f00fb080501c9a57
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  DB_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  DB_DATABASE: "{{ .Values.postgresql.postgresqlDatabase }}"
  # User Defined
  JAVA_OPTS: ""
  DB_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost
  DB_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password

service:
  main:
    ports:
      main:
        port: 10208
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: "/usr/local/xwiki"

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: xwiki
  postgresqlDatabase: xwiki

portal:
  enabled: true
