image:
  repository: tccr.io/truecharts/leantime
  pullPolicy: IfNotPresent
  tag: 2.3.2@sha256:fe6f0b02fb781d3acfc3e8dd03942f0b18870bbead8c070210463c72c6d53763

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  LEAN_DB_DATABASE: "{{ .Values.mariadb.mariadbDatabase }}"
  LEAN_DB_USER: "{{ .Values.mariadb.mariadbUsername }}"
  LEAN_APP_URL: "{{ if .Values.ingress }}{{ if .Values.ingress.main.enabled }}https://{{ ( index .Values.ingress.main.hosts 0 ).host }}{{ end }}{{ end }}"
  LEAN_DB_HOST:
    secretKeyRef:
      name: mariadbcreds
      key: plainhost
  LEAN_DB_PASSWORD:
    secretKeyRef:
      name: mariadbcreds
      key: mariadb-password
  LEAN_SESSION_PASSWORD:
    secretKeyRef:
      name: leantime-secrets
      key: LEAN_SESSION_PASSWORD

service:
  main:
    ports:
      main:
        port: 10117
        targetPort: 80

mariadb:
  enabled: true
  mariadbUsername: leantime
  mariadbDatabase: leantime
  existingSecret: "mariadbcreds"

portal:
  enabled: true
