image:
  repository: tccr.io/truecharts/synclounge
  pullPolicy: IfNotPresent
  tag: 5.2.5@sha256:4523460192d760c3e6219495b12faf29ca4eea27faa09df54f449c266f0a5994

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  AUTH_LIST: ""

service:
  main:
    ports:
      main:
        targetPort: 8088
        port: 8088

persistence:
  varrun:
    enabled: true

portal:
  enabled: true
