apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: plex-meta-manager
version: 2.0.8
appVersion: "1.18.1"
description: Python script to update metadata and automatically build collections.
type: application
deprecated: false
home: https://truecharts.org/charts/incubator/plex-meta-manager
icon: https://truecharts.org/img/hotlink-ok/chart-icons/plex-meta-manager.png
keywords:
  - plex-meta-manager
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/plex-meta-manager
  - https://hub.docker.com/r/meisnate12/plex-meta-manager
  - https://github.com/meisnate12/Plex-Meta-Manager
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.1.2
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
