image:
  repository: tccr.io/truecharts/plex-meta-manager
  pullPolicy: IfNotPresent
  tag: 1.18.1@sha256:46b293d5f5c9b432b3f15b1bfe806746148fa4fbf6ededf4cb88c9fd1bec4900

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  PMM_CONFIG: "/config/config.yml"
  # PMM_TIME: ""
  PMM_RUN: true
  PMM_NO_COUNTDOWN: true

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

persistence:
  config:
    enabled: true
    mountPath: /config

initContainers:
  1-create-init-config-file:
    image: "{{ .Values.ubuntuImage.repository }}:{{ .Values.ubuntuImage.tag }}"
    volumeMounts:
      - name: config
        mountPath: "/config"
    command: ["/bin/sh", "-c"]
    args:
      - |-
        echo "Creating config.yml file..."
        if [ -f /config/config.yml ]; then
          echo "Config file exists!, Skipping..."
        else
          echo "Config file is missing, getting a new one!"
          curl -fLvo /config/config.yml https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/config/config.yml.template || ( echo "Downloading config file, FAILED..." && exit 1 )
        fi

portal:
  enabled: false
