image:
  repository: tccr.io/truecharts/dillinger
  pullPolicy: IfNotPresent
  tag: v3.39.1@sha256:b1ad14e372dadf72223b06170a825e48bff486f603e5bfe4d7c3316988d85eba

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10143

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
