image:
  repository: cwq1913/lama-cleaner
  pullPolicy: IfNotPresent
  tag: cpu-0.26.1@sha256:e57095636fe19e62280e78f10f98fff0fe1e0608e689515b2a0a56a7d2dad2e8

gpuImage:
  repository: cwq1913/lama-cleaner
  tag: gpu-0.26.1@sha256:65c54a6309f46bb643be31d704e4b361988b277f7b9492a9dd8e24c28220005c
  pullPolicy: Always

imageSelector: image

command: lama-cleaner

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

lamacleaner:
  model: lama
  input: ""
  sd_run_local: false
  hf_access_token: ""
  sd_disable_nsfw: false
  sd_cpu_text_encoder: false
  sd_enable_xformers: false
  debug: false

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 10604

persistence:
  torch:
    enabled: true
    mountPath: /root/.cache/torch
  huggingface:
    enabled: true
    mountPath: /root/.cache/huggingface

portal:
  enabled: true
