image:
  repository: tccr.io/truecharts/calibre
  tag: 6.10.0@sha256:7b443dbcf988718d2c4a81a7adf378de35ab96ac55889e539f93c6484d91513c
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  PASSWORD: ""

env:
  CLI_ARGS:

service:
  main:
    ports:
      main:
        port: 8084
        targetPort: 8080
  webserver:
    enabled: true
    ports:
      webserver:
        enabled: true
        port: 8081
        targetPort: 8081

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
