image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/recyclarr
  tag: 4.0.2@sha256:8147069fc4418e9cefebdb25154c80fd33faf3219d697369c0604ee2ad4c857a

podSecurityContext:
  runAsGroup: 568
  runAsUser: 568

env:
  CRON_SCHEDULE: "@daily"

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

installContainers:
  initconfig:
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    volumeMounts:
      - name: config
        mountPath: "/config"
    command: ["recyclarr", "create-config"]

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  enabled: false
