image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/searxng
  tag: latest@sha256:2d9a45e663a5165ee63f0e41c8577bade9ca1d4dfa1d8f952cc6f20830cd4bce

env:
  BASE_URL: ""
  INSTANCE_NAME: SearXng

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  main:
    ports:
      main:
        port: 8080
        protocol: TCP
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: /etc/searxng

portal:
  enabled: true
