image:
  repository: tccr.io/truecharts/beets
  pullPolicy: IfNotPresent
  tag: v1.6.0@sha256:d72417e01a394de3be07ccbfd8bc69dd2f3349744d3c03249336de4f0294f767

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8337
        targetPort: 8337

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
