image:
  repository: tccr.io/truecharts/libreoffice
  pullPolicy: IfNotPresent
  tag: 7.2.7@sha256:e7b4d622a11572e6d41e6d4c843808e294c410e8f88c21345975567cc9b6773d

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10133

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
