env:
  KEYBOARD: ""
  SUBFOLDER: ""
  UMASK: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/kdenlive
  tag: latest@sha256:7363e9dea06d18639f2afe474bf56f2443fbf393d43be3f9805746e647a07fca
persistence:
  config:
    enabled: true
    mountPath: /config
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 3000
        protocol: TCP
        targetPort: 3000

portal:
  enabled: true
