env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/farmos
  tag: latest@sha256:8ad69f1f57595ef6d7a73915bfdf6cde8a76b84847b7c3b1d68904363233a06d
persistence:
  sitesdirectory:
    enabled: true
    mountPath: /var/www/html/sites
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 80
        protocol: TCP
        targetPort: 80

portal:
  enabled: true
