env:
  DELUGE_RPC_HOSTNAME: ""
  DELUGE_RPC_PASSWORD: ""
  DELUGE_RPC_USERNAME: ""
  DELUGE_RPC_VERSION: v2
  STORM_API_KEY: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/storm
  tag: latest@sha256:8fb10d28856f5d9f695fccad79c95b2310f46441c206152e1e37235c571bed1e
persistence: {}
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8221
        protocol: TCP
        targetPort: 8221

portal:
  enabled: true
